### ISSUE TITLE
Crash with Default Options

### ISSUE THREAD

**Issue by FaultyFunctions** [wyatt-herkamp/too-many-shortcuts#10]
If you have this and [Default Options](https://modrinth.com/mod/default-options) installed, you get a crash.

```java
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: de/siphalor/amecs/api/AmecsKeyBinding
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: de/siphalor/amecs/api/AmecsKeyBinding
	at net.blay09.mods.defaultoptions.fabric.compat.AmecsIntegration$1.setDefaultKeyModifiers(AmecsIntegration.java:18)
	at net.blay09.mods.defaultoptions.keys.KeyMappingDefaultsHandler.loadDefaults(KeyMappingDefaultsHandler.java:132)
	at net.blay09.mods.defaultoptions.DefaultOptionsInitializer.loadDefaults(DefaultOptionsInitializer.java:30)
	at net.blay09.mods.defaultoptions.DefaultOptionsInitializer.postLoad(DefaultOptionsInitializer.java:22)
	at net.blay09.mods.balm.fabric.event.FabricBalmEvents.fireEventHandler(FabricBalmEvents.java:41)
	at net.blay09.mods.balm.fabric.event.FabricBalmEvents.lambda$fireEventHandlers$0(FabricBalmEvents.java:36)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at net.blay09.mods.balm.fabric.event.FabricBalmEvents.fireEventHandlers(FabricBalmEvents.java:36)
	at net.blay09.mods.balm.fabric.event.client.FabricBalmClientEvents.lambda$registerEvents$5(FabricBalmClientEvents.java:85)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35)
	at net.minecraft.class_310.handler$bbj000$fabric-lifecycle-events-v1$onStart(class_310.java:12194)
	at net.minecraft.class_310.method_1514(class_310.java:864)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	... 2 more
Caused by: java.lang.ClassNotFoundException: de.siphalor.amecs.api.AmecsKeyBinding
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 16 more
```

**Comment by wyatt-herkamp** [comment]
So when moved a bunch of code to merge amecs-api, amecs, and nmuk. I broke compatibility with amecs-api actual API. 

I will fix this tomorrow. I will need to either make a PR to Default Options to move their Amecs code to too-many-shortcuts or add compatibility for some more of amecs api

**Comment by wyatt-herkamp** [comment]
So this latest commit will fix it crashing on load. However, Default Options may not load the options correctly but at least it won't be crashing.

**Comment by FaultyFunctions** [comment]
Thanks! Is the plan to eventually have those options loaded correctly?

**Comment by wyatt-herkamp** [comment]
> Thanks! Is the plan to eventually have those options loaded correctly?

Yes! I didn't get much sleep last night so I did not have the energy to get it fully working. However, I did not want you left with a crashing mod. I will try to get it fully working this week

**Comment by wyatt-herkamp** [comment]
- [ ] Add the Amecs API Back
- [ ] Submit PR to Default Options to use the TMS API once Released. 

Blocked by #31
